# Generated by Django 4.0.6 on 2022-08-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictususer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
